CREATE TABLE IF NOT EXISTS runmbles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    r1 VARCHAR(255) NOT NULL,
    r2 VARCHAR(255) NOT NULL,
    r3 VARCHAR(255) NOT NULL,
    running_time VARCHAR(255) NOT NULL,
    running_intensity VARCHAR(255) NOT NULL,
    start_time DATETIME NOT NULL,
    status ENUM('PENDING', 'MATCHED', 'CANCELED', 'TIMEOUT') NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;